### ISSUE TITLE
Lab 2: 2 recommended corrections

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#1]
## Lab/Demo: 02

Description of issue

**Exercise 1, Task 1, Step 4:**  Region column says 'the name of the Azure region into which you deployed the virtual machine in the previous task', and since there is no previous task this should be changed to something either neutral like 'Choose a region near you' or could also include the link to the Task 2/Step 2 note, regarding appropriate regions to choose. 

**Exercise 2, Task 2, Step 12:** There is no 'Microsoft Dependency agent (preview)' option to set on.  (I didn't see one that looked similar, either)

**Comment by TJGitHubUser** [comment]
Thanks for the feedback. Will look into this and update as appropriate.

**Comment by TJGitHubUser** [comment]
Exercise 1, Task 1, Step 4, changed instruction in Azure region column to say "choose a region near you" (lak)
Exercise 2, Task 2, Step 12: to be addressed later when UI can be verified.

**Comment by MOC-Labs-Review** [comment]
MOC Labs review has solved this issue with pull requests #9 and #10.
