### ISSUE TITLE
Lab 3: One minor addition

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#2]
# Module: 00
#### Step: 04

Description of issue
Might be good to add that one still needs to select the server before able to click OK.  i.e add _select **SEA-SVR2**_ to the end:

like so:

On **SEA-SVR2**, switch to the **Failover Cluster Manager** console, right-click or access the context menu for **FSCluster**, select **Move**, select **Select Node**, select **SEA-SVR2**, and then select **OK**.

**Comment by TJGitHubUser** [comment]
Good clarification. Will look to update this in the next week. Thanks for the feedback.

**Comment by TJGitHubUser** [comment]
Lab 3, ex. 4, task 1, included suggested addition.
