### ISSUE TITLE
Lab Module 09 Exercise 02, Task 02 Step 04 error in WAC

### ISSUE THREAD

**Issue by sotiris84** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#26]
# Module: 09
## Lab/Demo: 09
Exercise: 02
#### Step: 04

Description of issue
I receive an error in WAC when I try to set up Azure Monitor. The error is:

"Azure monitoring has encountered error. Log entry string is too long. A string written to the event log cannot exceed 32766 characters.."

Repro steps:

1. Just follow the steps
1.
1.

**Comment by TJGitHubUser** [comment]
If referring to Exercise 3, Task 2, step 4, we didn't get this issue you described.
