### ISSUE TITLE
Lab 6 Upgrade and migrate in Windows Server - Deployment Failed

### ISSUE THREAD

**Issue by tumultuous1** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#27]
# Module: 06
#### Step: 16

I have attempted this deployment 15 or 20 times and it seems to fail more often than not.   Any advice?

![Screenshot_2](https://user-images.githubusercontent.com/103527215/180244076-933fe539-ae0e-4acb-9192-9e4127068cf9.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/103527215/180244109-dd1a4298-7553-468f-a3c3-a8c56c7d4ac1.jpg)

**Comment by garjam73** [comment]
I also get an issue here. But I have a different error. 
On review and create I cannot access some resources in the template we are aksed to use

{"code":"MultipleErrorsOccurred","details":[{"code":"InvalidContentLink","message":"Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/application-workloads/active-directory/nestedtemplates/vnet.json'. The tracking Id is '19335744-dd56-4e89-8fdb-dbd3d5eeb2c1'. Please see https://aka.ms/arm-deploy for usage details."},{"code":"InvalidContentLink","message":"Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/application-workloads/active-directory/nestedtemplates/vnet-with-dns-server.json'. The tracking Id is '19335744-dd56-4e89-8fdb-dbd3d5eeb2c1'. Please see https://aka.ms/arm-deploy for usage details."}],"message":"Multiple error occurred: BadRequest,BadRequest. Please see details."}

**Comment by maas76** [comment]
At first, we had the same issue where the deployment of dc1 fails. I just created the VM manually and used the settings provided in the lab. Luckily there is no hidden infrastructure that will make the lab fail in there. It takes a bit longer to complete so allow about 1:45 hours for the lab. You also have to join the second VM to the domain before you can promote it to a domain controller. Assign dc2 a static IP address to achieve this. After that, everything worked great.

**Comment by AMorin8787** [comment]
Any update on this? I'm also experiencing the same error. It looks like theres already a PR to fix it, it just hasn't been committed [ ](https://github.com/az140mp/azure-quickstart-templates/pull/3/files)

**Comment by TJGitHubUser** [comment]
This will be fixed shortly in PR# 35.
