### ISSUE TITLE
Module 9 Lab 3 Task 2 Step 3 guest-level monitoring not present

### ISSUE THREAD

**Issue by autosysops** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#33]
# Module: 09
#### Step: 03

Description of issue
guest-level monitoring not present.
It looks like this is enabled by default by a newer version of the extension

Repro steps:

1. Enable the logging from the portal
1. Wait for a couple of minutes
1. Go to the logs tab, the guest-level monitoring is not present

**Comment by autosysops** [comment]
> 

It is provided right? Module 9, Exercise 3 task 2 step 3

**Comment by TJGitHubUser** [comment]
This will be fixed shortly in PR# 35.
