### ISSUE TITLE
Lab 05 - Mars agent installation verification failed

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#34]
# Module: 05
#### Step: 12

Description of issue

I encountered an error while installing "Azure Site Recovery Provider Setup(Hyper-V server)"
Error message: "Mars agent installation verification failed. Expecting version 2.0.9259.0, found 0.0 "

### Relevant screenshots

![image](https://user-images.githubusercontent.com/111972688/209991509-861c8b9a-6fdc-4259-a783-9e47a5e83140.png)

### Logs file  screenshot

![image](https://user-images.githubusercontent.com/111972688/209991621-6b633b9b-09f5-40ba-8dd9-1093eb8c5cad.png)

**Comment by TJGitHubUser** [comment]
This will be fixed shortly in PR# 35.
