### ISSUE TITLE
LAB_AK_06_Upgrade_and_migrate_Windows%20Server.md - Several Azure UI/Minor updates noticed in QA

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#39]
# Module: 00
#### Step: Various

Description of issue

In a recent QA of this lab, several minor issues were noted where Instructions updates might be deemed useful to fix:

**- Exer 1, Task 3, Step 3:**  Instructions in the **Resource Group** portion of the table say to create using '_the name of a new resource group AZ801-L0601-RG_', however this RG was already created in a previous task/step so Instructions should say '_Use existing_'

**- Exer 1, Task 4, Step 9:** Azure UI has changed very slightly, it may be good to rephrase this step from: '_On the Bastion tab of the az801l06a-dc2 | Connect page, select Use Bastion_.'

To: '_On the Bastion tab of the az801l06a-dc2 | Connect page, select Bastion._'

Then also in Step 10, perhaps change the text '_When prompted, provide the following credentials, and then select Connect_'

To:  '_On the **Bastion** page, provide the following credentials, and then select Connect'_

Also note **Edge** browser in the **SEA-SVR2** VM is configured by default to block popups, so it may be a good idea to add a 'note' immediately after **Step 9** indicating something similar to this:

    > **Note**: **Edge** by default will block popups. To allow popups for **Bastion** go to **Settings** in **Edge**, select **Cookies and site permissions** on the left, **Pop-ups and redirects** under **All permissions** and finally toggle **Block (recommended)** off.

**- Exer 1, Task 4, Steps 29 + 30** - Identical issue to the above.

**- Exer 2, Task 3, Step 4:** change "in" to "In"

**Comment by v-asamim** [comment]
The issue has been resolved in PR https://github.com/MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services/pull/43
