### ISSUE TITLE
Lab 7: 2 minor issues, one reasonably major

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#4]
# Module: 00
#### Step: (various)

Minor issues:

**Exercise 3, Task 1, Step 6:** Edge doesn't prompt by default, may wish to include an elaboration to student to manually copy the file to F:\VMs folder

**Exercise 3, Task 1, Step 17:** cannot start the VM within the mem limits of the HV VM.  Need to include a step to change memory to (say) 4096

**More major issue:**
The manifest lists Lab 7 as recommended for 120 minutes, while in testing we found is required more like 3.5 hours to be able to complete.  The delays were caused in the main by _very_ slow response for screen rendering within the nested Azure HV VM/Bastion session/further VM nesting, where response time to type/render windows/etc. declined in some cases to a level that was almost unbearable.

I realize that this is very much a function of the background network speed in various places - however it seemed consistently slow, at least this week, and it may be good to put some form of warning regarding this possibility to students/instructors.  

Also note that in my case (though it was being tested within an ALH-hosted environment, which can itself occasionally have poor network performance) I could reproduce the exact same painfully slow rendering when accessing the Bastion session in Azure _direct from my laptop_, and from several _other locations completely outside of the ALH enviros network_ -- indicating strongly it was networking slowness within Azure itself, at least in that region. (eastus/eastus2)

There may not really be a lot that can be done to *solve* for the issue, although perhaps there are ways to optimize for this in Azure networking config?  In any case, it is probably worth warning about in the instructions.  I should note that the problem was at its worst when either:

-  A high-color/image was present on the login screen (or desktop) of one of the freshly provisioned HyperV (or Azure) VMs -- which is often solved by ALH's in locally-hosted VMs by setting that login image/desktop to a solid single color in place of picture.
- Opening a browser whose default page- such as Edge's default MSN page - (or page you need to access) is also some form of high-color graphic(s), w/moving graphics, or some combination of the above.  ALH's often solve for this by setting default home page/new tab page to 'about:blank' to avoid this.

**Comment by TJGitHubUser** [comment]
Thanks for the feedback. We'll address the issues raised. Regarding the timing required to complete the lab and any adjustments, as pointed out, this may not be solved in the short term, but will look at any optimizations that would improve performance.

**Comment by TJGitHubUser** [comment]
Ex. 3, Task 1, Step 6: added note about manually copying the VHD file.
ex. 3, Task 1, step 17: added step about increasing VM memory limit
