### ISSUE TITLE
LAB_AK_07_Implementing_migration_in_hybrid_scenarios.md - Several Azure UI/Minor updates noticed in QA

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#40]
# Module: 
#### Step: various

Description of issue

Several issues were noted in a recent QA of this lab.  In the main, it appears they are related to Azure UI/naming changes since the original release of the course.  They are detailed in this table:

| Exercise # | Task # | Step # | Issues   Identified |
|---|---|---|---|
| 1 | 3 | 2 | change "On the   az801l07a-hv-vm page, select Connect and then, in the drop-down menu, select   Bastion. On the Bastion tab of the az801l07a-hv-vm \| Connect page, select Use   Bastion."            to "On the az801l07a-hv-vm page, select Connect and then, in the   drop-down menu, select Bastion. |
| 3 | 2 | 2 | change "On the Basics tab   of the Create assessment page, next to the Assessment properties label,   select Edit."            to "On the Basics tab of the Create assessment page, next to the   Assessment settings label, select Edit." |
| 3 | 2 | 3 | change "properties" to   "settings"            Also, had to enter Savings options (Compute) so I chose None. |
| 4 | 1 | 2 | change "On the Azure   Migrate \| Servers, databases and web apps page, in the Azure Migrate: Server   Migration section, select the Discover link."            to "On the Azure Migrate \| Servers, databases and web apps page, in   the Migration and modernization section,   select the Discover link." |
| 4 | 1 | 15 | change "Azure Migrate:   Server Migration" to "Migration and modernization" |
| 4 | 2 | 1 | change "Azure Migrate:   Server Migration" to "Migration and modernization" |
| 4 | 2 | 2 | change "On the Source   settings tab of the Replicate page, in the Are your machines virtualized?   drop-down list, select Yes, with Hyper-V and then select Next."            to "On the Specify intent page, select Continue.  On the Basics tab of the Replicate page, in the Are your machines   virtualized? drop-down list, select Yes, with Hyper-V and then select   Next." |
| 4 | 2 | 9 | change the first occurrence of   "Azure Migrate: Server Migration" to "Migration and   modernization" |
| 4 | 3 | 11 | change "On the Migrate   page, ensure that Yes is selected in the Shutdown machines before migration   to minimize data loss? drop-down list, select the checkbox next to the VM   name az801l07a-vm1, and then select Migrate."            to "On the Migrate page, ensure that Yes is selected in the Shutdown virtual machines and perform a planned migration with no data loss? drop-down list, and then select Migrate." |
| 4 | 3 | 12 | change the first occurrence of   "Azure Migrate: Server Migration" to "Migration and   modernization" and in the Note. |

**Comment by v-asamim** [comment]
The issue has been resolved in PR https://github.com/MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services/pull/43 
Thank you for your support.
