### ISSUE TITLE
LAB_AK_05_Implementing_Azure-based_recovery_services.md - Virtual Networks creation, Intermittent new UI presented

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#41]
# Module: 00
## Lab/Demo: 05
Exercise 2
#### Steps: 02-08

Description of issue

This is likely something that cannot be (efficiently) resolved in Instructions until the Azure UI 'stabilizes' but I at least wanted to call it out as a potential issue:  When creating an Azure **Virtual Network**, there is both an old UI and a new UI.  The old UI matches the instructions here in **Exercise 2, Task 1, Steps 2-8.**

Unfortunately, since ~Oct 2022 last year there can appear intermittently a *new* UI that has slightly revised the order of tabs and the click-through a student must take to successfully create a **Virtual Network**.  The changes are relatively minor so hopefully the majority of Students are able to navigate the new process successfully.

I was just testing this morning and out of 10 launches, none had the new UI.  A few days ago, the same test had 2 launches with the new UI so unfortunately, we have no way to be sure what appears in any given launch.  I haven't been able to find any way to force the old (or the new) UI, so unless a whole subset of Instructions was written to deal with both potential UIs a student might get, the alternative is just to await the new UI becoming ubiquitous.

I posted about the issue here, and apparently the docs.microsoft.com people are aware of it so likely we just have to be patient until the new UI occurs consistently:  https://github.com/MicrosoftDocs/azure-docs/issues/105704

**Comment by TJGitHubUser** [comment]
Good observation and summary of what has occurred. Agree that it's best to wait until the UI catches up. Thanks for pointing out this issue.
