### ISSUE TITLE
Lab06 template issues

### ISSUE THREAD

**Issue by J0eGos** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#46]
# Module/Lab: 06
### Task: 01

Description of issue
Multiple errors through the beginning of Lab 06. 
Repro steps:

1.Guide mentions that on line 199 it should say "2022-datacenter" However viewing the parameters will show 2019

1. Trying to deploy the template fails with errors regarding the Vnet.json and vnet-with-dns-server-json.

Is this lab due an update soon? these issues are preventing users from completing the full course.

### Relevant screenshots

![image](https://github.com/MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services/assets/128402777/0bc631d3-59f3-4e16-9b40-9cddf5214eb2)

**Comment by ahsan296** [comment]
Any update on this we are experiencing similar issue on our end?

**Comment by ahsan296** [comment]
Any update?

**Comment by dvimacedo** [comment]
Tested in multiple environments, problem couldn't be replicated.
