### ISSUE TITLE
Mod 4, Ex 4 - Deprecation of MMA-related features as part of agent retirement

### ISSUE THREAD

**Issue by Yiizo** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#48]
# Module/Lab: 02
Exercise 4: Onboarding on-premises Windows Server into Microsoft Defender for Cloud and Azure Automation

Description of issue

As we approach the agent's retirement in August 2024, the following MMA-related features will be removed from the Defender for Cloud portal.
The ability to onboard new non-Azure servers to Defender for Servers via Log Analytics workspaces will be removed from both the Inventory and Getting Started blades.

https://learn.microsoft.com/en-us/azure/defender-for-cloud/release-notes#deprecation-of-mma-related-features-as-part-of-agent-retirement

**Comment by TJGitHubUser** [comment]
Please see an updated readme file that gives some details regarding this issue. Apologies that we don't have an updated solution quite yet but are working as quickly as possible to resolve. We will post a communication when the labs are updated. Thanks.
