### ISSUE TITLE
LAB_09_Implementing_operational_monitoring_in_hybrid_scenarios must be updated to Azure ARC with a Data Collector

### ISSUE THREAD

**Issue by PurvesG2** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#49]
# Module/Lab: 09
#### Step: 01

Description of issue

Use of MMA is deprecated, and the lab no longer works

Replace Lab with On-Boarding for Azure ARC and configuring an Azure Monitor Data Collection Rule

**Comment by TJGitHubUser** [comment]
Please see an updated readme notification that just went out on GitHub. It gives some details regarding this issue and the plans to update the labs. Apologies that we don't have an updated solution quite yet but are working as quickly as possible to resolve. We will post a communication when the labs are updated. Thanks.
