### ISSUE TITLE
Lab 9: various minor issues

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#5]
# Module: 00
#### Step: (various)

Description of issue

**Exercise 2, Task 1, Step 3**: As with other labs in the 800/801 series:  immediately after installing the latest version of the **WAC** tool, we consistently receive error **ERR_CONNECTION_REFUSED**.  But, a reboot of **SEA-SVR2** seems to solve it.  Probably worth adding this to instructions.

**Exercise 2, Task 2, Step 4:** The RG listed to choose is 'AZ801-L090**1**-RG', however we cannot select the LAW we created earlier unless we choose 'AZ801-L090**2**-RG'.  I am assuming this step has the typo and should be 'AZ801-L090**2**-RG'.

**Exercise 3, Task 2, Step 13:** At least in our tests, the **Azure Monitor (Preview)** option is greyed out until we followed the steps in the **Click to configure a managed identity in Azure AD for this VM** link that appeared just below. 

**Exercise 3, Task 2, Step 20:** it is no longer 'Virtual Machines' but instead is now 'VM insights'.

**Exercise 4, Task 1, Step 7:**  Seems to have a redundant step, i.e. this:
    _select **Add action groups**, and then select the **+ Create action group** button._

should just be this
_select the **+ Create action group** button._

**Comment by TJGitHubUser** [comment]
Thanks for the feedback. Will address as appropriate and update you.

**Comment by TJGitHubUser** [comment]
Exercise 2, Task 1, Step 3: added note to lab and lak
Exercise 2, Task 2, Step 4, fixed typo in lab and lak
Exercise 3, Task 2, Step 13: will need to verify steps in UI (applies only lak)
Exercise 3, Task 2, Step 20: fixed in lab and lak
Exercise 4, Task 1, Step 7: fixed (lak only)
