### ISSUE TITLE
Lab 06 - Errors while Creating New Partition via PowerShell

### ISSUE THREAD

**Issue by KashifKhaan** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#50]
# Module/Lab: 060
#### Step: 12

Description of issue
Facing errors when trying to create a new partition using PowerShell commands. Specifically, the commands fail due to either the disk number not being found or insufficient available capacity.

### Relevant screenshots
![Screenshot_13](https://github.com/user-attachments/assets/5069154e-3982-416d-b763-c86a6af3a14f)

**Comment by dvimacedo** [comment]
Hi, thank you for reaching out with your issue.
After testing, the lab is working fine, please take note of exercise 1 task 3 - step 4 , the addition of a new disk during the deployment of the VM. Everything should run as expected.


![image](https://github.com/user-attachments/assets/e8b79ba6-326c-4e28-b70f-934310b65df7)
