### ISSUE TITLE
Change Tracking and Inventory (CT&I) with MMA/OMS has retired

### ISSUE THREAD

**Issue by jstanesic** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#51]
# Module/Lab: 02
#### Step: 04

Description of issue:
A Change Tracking and Inventory (CT&I) with MMA/OMS has retired on 31st August 2024. New VM onboarding is no longer supported. For retirement details, refer here.

Repro steps:

1. Create an automation account
2. Open Configuration Management
3. Open Inventory

### Relevant screenshots
![image](https://github.com/user-attachments/assets/9b17e33e-0a70-411d-9def-1238b06d70c4)

**Comment by Sanjanadhananjayaa** [comment]
Is there any update on the issue reported above?

**Comment by Srikanthssp** [comment]
Hi @TJGitHubUser , can u please provide an update for this issue

**Comment by TJGitHubUser** [comment]
Labs are currently being rewritten to account for MMA retirement. While I can't give an exact date they will be republished, I think we're probably looking at weeks at the most. The labs are required to go through a security compliance/testing phase with our ALH provider. We will post a heads-up when we have a better idea of when the updated labs will be available.
Thanks.

**Comment by Srikanthssp** [comment]
Hi @TJGitHubUser , any latest update on this. When can we expect the latest changes ?

**Comment by TJGitHubUser** [comment]
Both lab2 and lab9 are being significantly rewritten and retested. We're hoping to submit both labs to the ALH providers for verification within the next couple of weeks, but I can't give an exact estimate of release. I hate to say by end of year but given testing, security, accounting for holiday timeframes and then working through our release teams I'd say we're working to have new updates as quickly as possible. Thanks for your understanding.
