### ISSUE TITLE
Incorrect name

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services#7]
# Module: 02
#### Step: 1

Description of issue

Incorrect instructions, instead of SEA-ADM1 (that doesn't exists), it should say SEA-SVR2 from where we previously downloaded the agent installer.

Repro steps:

Task 2: Perform unattended installation of the Log Analytics agent
In this task, you will perform unattended installation of the Log Analytics agent.

On SEA-ADM1, start Windows PowerShell as administrator.

**Comment by TJGitHubUser** [comment]
Merged PR to fix incorrect server name. Thanks.
